# Generated by Django 4.2.5 on 2024-01-21 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-postedOn']},
        ),
        migrations.AddField(
            model_name='post',
            name='imageContent',
            field=models.ImageField(null=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 21, 17, 18, 22, 517821)),
        ),
        migrations.AlterField(
            model_name='post',
            name='textContent',
            field=models.TextField(),
        ),
    ]
