# Generated by Django 4.2.3 on 2023-07-15 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageContent',
            field=models.ImageField(null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 15, 13, 11, 12, 95912)),
        ),
        migrations.AlterField(
            model_name='post',
            name='textContent',
            field=models.TextField(),
        ),
    ]
