# Generated by Django 4.2.3 on 2023-07-15 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_post_imagecontent_alter_post_postedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageContent',
            field=models.ImageField(null=True, upload_to='All files/project/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 15, 13, 13, 35, 838538)),
        ),
    ]
