# Generated by Django 4.2.5 on 2024-01-21 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_post_options_post_imagecontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 21, 17, 23, 36, 753174)),
        ),
    ]
