# Generated by Django 4.2.3 on 2024-01-19 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_alter_post_imagecontent_alter_post_postedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 8, 45, 3, 339488)),
        ),
    ]
