# Generated by Django 4.2.3 on 2024-01-20 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_alter_post_postedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 20, 4, 46, 45, 30246)),
        ),
    ]
